### ISSUE TITLE
Add in-app language switcher to android components

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/android-components#1557]
Talked with @st3fan about this at All-Hands, and he suggested I file an issue to get this in :)
This is basically to get an in-app language switcher, like what we currently have in many mobile products (Firefox Android, Focus Android, Firefox Lite, etc).

Also, CC @Pike and @gueroJeff so they are aware of this.

**Comment by pocmo** [comment]
Adding to triage list since that is something we may want for Fenix soon.

Since we now are able to re-create activities and do not need to handle config changes ourselves, implementing this may be much easier now.

**Comment by Amejia481** [comment]
This work can be split into three pieces:

- [ ] API for switching languages programmatically #3584.
- [ ] Preference widget language switcher #3585.
- [ ] Gradle plugin to auto detect with language the app support #3586

**Comment by gueroJeff** [comment]
Wanted to also raise that when we did this for Fennec, there were some locale code mapping issues between Android and our locales (e.g., Hebrew is 'he' for us was 'iw' for Android). We're the standards compliant party (the ISO move from 'iw' to 'he' in 1989), but we should make sure that locale codes can map appropriately.

**Comment by Amejia481** [comment]
Thanks @gueroJeff !

**Comment by Amejia481** [comment]
Useful blog post related how to handle language switching on Android
https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758
