### ISSUE TITLE
Meta: Progressive Web Apps (PWA)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1819]
### Description

> Progressive web apps use modern web APIs along with traditional progressive enhancement strategy to create cross-platform web applications. These apps work everywhere and provide several features that give them the same user experience advantages as native apps.

### Resources

- https://developer.mozilla.org/en-US/docs/Web/Apps/Progressive
- https://developer.mozilla.org/en-US/docs/Web/Manifest
- https://www.goodbarber.com/blog/progressive-web-apps-feature-compatibility-based-on-the-browser-a883/

### Target

- https://github.com/mozilla-mobile/fenix/issues/223

### User Stories

PWA MVP (Must)
* [x] https://github.com/mozilla-mobile/fenix/issues/778 - As a user I want to install a PWA to my home screen
* [x] https://github.com/mozilla-mobile/fenix/issues/768 - As a user I want to install a PWA-able website with just one click (badging)
* [x] https://github.com/mozilla-mobile/fenix/issues/769 - As a user I want to use my installed PWAs while being offline
* [x] https://github.com/mozilla-mobile/fenix/issues/770 - As a user I want to use my installed PWAs in fullscreen / standalone mode
* [x] https://github.com/mozilla-mobile/fenix/issues/779 - As a user I want to be able to refresh the currently displayed page in a PWA 
* [x] https://github.com/mozilla-mobile/fenix/issues/781 - As a user I want to get visual feedback that a PWA is starting
* [x] https://github.com/mozilla-mobile/fenix/issues/777 - As a user I want external URLs in a PWA to open in a custom tab.
* [x] https://github.com/mozilla-mobile/fenix/issues/6440 - As a user I want to receive web notifications from a PWA site.

Maybe
* [x] https://github.com/mozilla-mobile/fenix/issues/780 - As a user I want to share from my installed PWA to other installed (native) apps

After Fenix MVP
* [x] https://github.com/mozilla-mobile/fenix/issues/775 - As a user I want Progressive Web Apps installed from the Google Play store to use my default browser
* [x] https://github.com/mozilla-mobile/fenix/issues/771 - As a user I want to receive web push notifications for installed PWAs

#### Needed
- [x] #1828 - Expose Web App Manifest in Session
- [x] #1830 - Support display modes
- [x] #824 - Pull to refresh
- [x] To be filled: Support orientation (manifest)
- [x] #2293: Opening external links in custom tab.
- [x] mozilla-mobile/fenix#394: Add Trusted Web Activity (TWA) support

#### Nice-to-have
- [ ] #2294: Splash screen (App launching screen)

#### Later
- [x] #3486: WebShare API
- [ ] To be filed: Web Push

### Dependencies

- [x] [Bug 1522451 - GeckoView: Web app manifest (PWAs)](https://bugzilla.mozilla.org/show_bug.cgi?id=1522451)
- [x] [Bug 1522446 - GeckoView: Pull to refresh](https://bugzilla.mozilla.org/show_bug.cgi?id=1522446])
  - [x] #1824 - Meta: Pull To Refresh

**Comment by st3fan** [comment]
@pocmo WebAPK was left out of the MVP but we need to understand if that is actually a requirement for implementint PWAs. Also on whjat Android version that is supported.

**Comment by bbinto** [comment]
We might have to split this meta into 2 meta's so it's not spanning over 2 milestones and can be better tracked.

**Comment by shorlander** [comment]
@st3fan What kind of UX Feedback is needed here?

**Comment by pocmo** [comment]
@shorlander I can think of at least:

* How do we want to surface that a website is "installable" as PWA? In other browsers I see two major ways: Showing a badge in the URL bar (which Fennec does for a lot of other things too) and/or showing a bottom sheet or snackbar (sometimes with some heuristics that it doesn't show up all the time).

* When adding the app to the home screen: What UI do we present the user? Other browsers at least show a confirmation dialog; often with the ability to edit the "title" that will be used on the home screen.

**Comment by andreasbovens** [comment]
> @st3fan What kind of UX Feedback is needed here?

We need to decide what the PWA's generated splash screen should look like as well. Typically, these are generated from assets referenced in the manifest. We need to decide how we want to arrange and animate these splash screens.

**Comment by andreasbovens** [comment]
@pocmo @bbinto 

Small sidetrack: we need to decide what we want to do with sites that don't have a valid manifest (and are normal sites or broken PWAs). In Fennec, we have an "Add shortcut" option for that reason, which simply generates an icon and title from the site's metadata and places a URL shortcut on the home screen. When launched, the URL in question is just opened in a new tab. Is this something we're planning as well?

**Comment by pocmo** [comment]
> In Fennec-powered PWAs, we open external URLs in a Custom Tab

@andreasbovens External URLs in this case are links that leave the scope defined in the manifest, right?

**Comment by lime124** [comment]
removing reference browser issues from UX feedback board. please ping stefan if you need support from a ux team member.

**Comment by pocmo** [comment]
@lime124 This is not reference browser :)

**Comment by liuche** [comment]
@pocmo adding a bit more context here, from meeting with the TWA folks at googlio.

To summarize, the things that they said we'd need to implement are:
- Custom Tabs API ✅
- Digital Asset Link Verification to ensure the website and the app come from the same developer. ("The actual logic here should be pretty easy to copy from Chromium", and we can get guidance if we need it)
- Hiding the browser chrome if the Digital Asset Link Verification succeeds.
- Ensuring that it comes back if the user navigates away from the origin they are verified with.

At this point you've got a basic, passable TWA implementation.
- Notification Delegation, so that push notifications from the website are handed to the app to display.
- Notification Delegation Auto-Enrolment, so that the website gets notifications enabled if the app is installed.
- Splashscreens (more of an optional feature, was apparently painful to implement)

Additional privacy/user data control features:
- The "Running in Chrome/Firefox" infobar that is shown on first run to alert the users that what they do in the app is seen by Chrome.
- When the user uninstalls the TWA (or clears data for it through Android settings), we display a dialog saying "This app also had data in Chrome, would you like to clear this too?"

**Comment by vesta0** [comment]
Thanks for summarizing @liuche !

@pocmo can we breakdown the GV requirements to accomplish the above?

**Comment by pocmo** [comment]
@vesta0 Filed this as a separate issue for now - feel free to drop it into the sprint if you think we should do that asap: https://github.com/mozilla-mobile/android-components/issues/3061

**Comment by vesta0** [comment]
Thank you @pocmo ! FYI PWA/TWA work are next high priority AFTER all MVP P1s are completed :)

**Comment by vesta0** [comment]
The PWA feature has been completed, thanks to amazing hard work by several cross-functional teams 🎉 🎉 🎉 

The only 2 remaining non-urgent items (Web Push and Splash Screen) will be addressed separately as we continue to enhance PWA experience in the future.
