### ISSUE TITLE
Meta: Custom Tabs

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1822]
### Current Status Board 
- https://github.com/orgs/mozilla-mobile/projects/7
- Owner of board: 

### Description

Custom Tabs allow an app to customize how the browser looks and feels. A Custom Tab will look like it is part of the third-party app while still providing all the features of the default browser (cookies, form autofill, ..).

* https://developer.chrome.com/multidevice/android/customtabs

### Target

https://github.com/mozilla-mobile/fenix/issues/222

### Tasks

- [x] Reference Browser: *"As an app developer I want to customize the look&feel of a custom tab."*
  - [x] #397 - Custom toolbar color
  - [x] #1398 - Custom menu items
  - [x] #1399 - Custom action button
  - [x] #1400 - Custom close button
  - [x] #1401 - Default share item
- [x] Reference Browser: *"As a User I want custom tabs to load fast"*
  - [x] #395 - Implement warmup()
  - [x] #1396 - Implement mayLaunchUrl()
- [ ] Fenix:  *"As a User I want to use Fenix as a Custom Tab"*
  - [x] mozilla-mobile/fenix#203 Custom Tab UI feedback/requirements
  - [x] mozilla-mobile/fenix#311 Integrate Custom Tabs feature

**Comment by vesta0** [comment]
Is this blocked on anything and what kind of UX feedback is required? UX mockups are here: https://github.com/mozilla-mobile/fenix/issues/203
