### ISSUE TITLE
Meta: Basic Sync Integration

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1823]
### Description

(...)

### Target

https://github.com/mozilla-mobile/fenix/issues/212

### Tasks

From the R-B Reference Story:

* [x] https://github.com/mozilla/application-services/issues/334 history sync support in the places lib
* [x] https://github.com/mozilla-mobile/android-components/issues/1375 `Syncable` android-components concept
* [x] https://github.com/mozilla-mobile/android-components/issues/1376 `feature-sync` in android-components
* [x] https://github.com/mozilla-mobile/reference-browser/issues/206 integrate `feature-sync` in reference-browser
* [x] https://github.com/mozilla-mobile/reference-browser/pull/425 SyncManager and AccountManager integration

More in A-C:

- [x] https://github.com/mozilla-mobile/android-components/issues/1376
- [x] https://github.com/mozilla-mobile/android-components/issues/1375
- [ ] https://github.com/mozilla-mobile/android-components/issues/1584
- [ ] https://github.com/mozilla-mobile/android-components/issues/1581
- [x] https://github.com/mozilla-mobile/android-components/issues/1320
- [x] https://github.com/mozilla-mobile/android-components/issues/1373
- [x] https://github.com/mozilla-mobile/android-components/issues/1372
- [x] https://github.com/mozilla-mobile/android-components/issues/1369
- [x] https://github.com/mozilla-mobile/android-components/issues/1089
- [x] https://github.com/mozilla-mobile/android-components/issues/1420
- [ ] https://github.com/mozilla-mobile/android-components/issues/1036
- [x] https://github.com/mozilla-mobile/android-components/issues/1780

### Reference Browser Integration / Testing

- [x] https://github.com/mozilla-mobile/android-components/issues/1223

(Needs a breakdown and potentially multiple metas? A lot of issues should exist already) - Yeah I think it would be nice if we could have labels for `sync`, `sync-history` `sync-logins`, `sync-tabs` - then we can sort of see those as separate tasks? @grigoryk ?
