### ISSUE TITLE
Meta: Screenshots

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1826]
### Description

(..)

### Target

- https://github.com/mozilla-mobile/fenix/issues/89

### Tasks

- [ ] #498 - Engine: Add support for taking screenshots 
- [ ] #1382  - Engine: Add support for capturing thumbnails

### Dependencies

- [ ] [Bug 1462018 - GeckoView: Add support for taking screenshot of web content (for tab thumbnail tray)](https://bugzilla.mozilla.org/show_bug.cgi?id=1462018)

**Comment by vesta0** [comment]
Waiting for [UX mocks ](https://github.com/mozilla-mobile/fenix/issues/183)

**Comment by cpeterso** [comment]
GV support for taking viewport screenshots (for page thumbnails in tab switcher UI) has landed ([bug 1462018](https://bugzilla.mozilla.org/show_bug.cgi?id=1462018)). Full page shots ([bug 1530967](https://bugzilla.mozilla.org/show_bug.cgi?id=1530967)) is still planned but it will be more work.
