### ISSUE TITLE
Engine/Session: Feature partity to support Focus

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#200]
While the Fenix roadmap is still not set in stone I would like us to work towards using `engine` and `session` in Focus/Klar. Having those components in production will help us more in this stage than building an unknown product.

There are a bunch of things missing and I try compile a list in this "meta" bug. We can file separate issues whenever we start to work on some of them.

_Note that this is a list of things by how they are written in Focus. It's possible that we want to do things in a different way here."_

### Session

* [x] Source of session (Used for telemetry)
* [x] #177 - secure (boolean) -> Used for the lock icon in the toolbar
* [x] security organization and origin; data from SSL certificate; Used in doorhanger
* [x] Number of trackers blocked (Is this something we would add? Do we want to add a way for an application to "enhance" the session data?)
* [x] #256 - Custom Tab Config. There's a lot of additional data in a custom tab intent that we need to customize the UI and other things.
* [ ] Engine state (That's something we may not need here)
* [ ] ~isRecorded - a boolean flag to know whether the session source was already reported to telemetry. That's something we may want to do differently.~ We have a telemetry component in the works.
* [x] #352 - isBlockingEnabled - Whether the global tracking protection switch is on/off
* [x] #499 - Private Browsing
* [ ] #494 - Website icon (favicon)
* [x] #495 - Website thumbnails for Tab Tray
* [x] #647 - Desktop mode
* [x] #656 - Find in page

### Engine

Callbacks (Mostly to update session):

* [x] Security state changed (isSecure, organization, host)
* [ ] onRequest(isTriggeredByUserGesture) - Used to clear search terms in session
* [x] #424 - onDownloadStart(Download)
* [x] #476 - onLongPress(HitTarget) - Used for context menus
* [x] #643 - fullscreen support. (onEnterFullScreen(FullscreenCallback, View), onExitFullScreen())
* [x] countBlockedTracker() - whenever a tracker was blocked
* [x] resetBlockedTrackers() - called from onPageStarted(), a separate callback may not be needed
* [x] onBlockingStateChanged() - To update the session
* [x] #673 - Request interception and content injection

Actions:
* [x] #657 - Forward lifecycle events (onResume, onPause, ..). This is primarily for WebView.
* [x] #604 - stopLoading
* [x] getUrl() - This may not be needed and should be queried from the session, I guess.
* [x] #644 cleanup() - Clears WebView data (because it doesn't support private browsing). This may be something we want to do differently now.
* [x] saveState() (Saves state as bundle in Session)
* [x] restoreState() (Restores state from bundle in Session)
* [x] #605 - loadData(...) - Loads HTML from a string (etc:) instead of a URL (Used for internal URLs)
* [x] #431 - getTitle() - Returns the title of the currently displayed website. Makes more sense in the session too.
* [x] #352 - Tracking Protection + tracking count
* [x] #521 - Enable/Disable JavaScript
* [x] #689 - Enable/Disable loading of web fonts
* [ ] #498 - Take screenshots

### Misc.

* [x] #662 - Always private browsing
* [ ] No session storage (to disk)

**Comment by grigoryk** [comment]
https://github.com/mozilla-mobile/android-components/issues/853 seems relevant too.

**Comment by pocmo** [comment]
Closing. Focus parity is not something we are striving for. And we may even have reached it by now. :)
