### ISSUE TITLE
[Meta] Port prompts from Fennec 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#3550]
This includes all the issues that need to be completed to bridge the gap between AC prompts and Fennec ones. I'm not sure if we want to port them as they are or  if we want some input from UX.

- [ ] [Port the DateTimePicker widget from Fennec](https://github.com/mozilla-mobile/android-components/issues/1532)
- [ ] [Port ColorPicker from Fennec and add Advanced mode](https://github.com/mozilla-mobile/android-components/issues/3480)
 - [ ] [Improve popup windows dialogs](https://github.com/mozilla-mobile/android-components/issues/3549)

**Comment by pocmo** [comment]
Closing the meta since we do not seem to need "meta" issues anymore. :)
