### ISSUE TITLE
Create a release checklist

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#527]
There are more and more tasks. Let's create a checklist like we did for Focus.

**Comment by pocmo** [comment]
_Draft_:

# Release checklist

## Before the release
- [ ] Update [CHANGELOG](https://github.com/mozilla-mobile/android-components/blob/master/CHANGELOG.md)
- [ ] Generate API docs for release
- [ ] Close milestone (Milestone should be 100% complete. Incomplete issues should have been moved in planning meeting)

## Release
- [ ] Create a new tag/release on GitHub.
- [ ] Wait for taskcluster to complete successfully and check that builds are on jcenter.
- [ ] Request new packages to be linked to jcenter (if there are any new ones)

## After the release
- [ ] Send release message to Slack.
- [ ] Send release message to mailing lists (Which lists?).
- [ ] Update version number in repository
