### ISSUE TITLE
Target Android 11

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8519]
These are all the issues that we have to fix before targeting Android 11

- browser-engine-system
    - [ ] https://github.com/mozilla-mobile/android-components/issues/8512
    - [ ] https://github.com/mozilla-mobile/android-components/issues/8513
    - [ ] https://github.com/mozilla-mobile/android-components/issues/8514

- browser-thumbnails
    - [x] https://github.com/mozilla-mobile/android-components/issues/9555

- feature-addons
    - [x] https://github.com/mozilla-mobile/android-components/issues/8516

- feature-downloads
    - [x] https://github.com/mozilla-mobile/android-components/issues/8515

- feature-qr
    - [x] https://github.com/mozilla-mobile/android-components/issues/8518
    - [x] https://github.com/mozilla-mobile/android-components/issues/8510

- lib-crash
    - [x] https://github.com/mozilla-mobile/android-components/issues/8511

- support-ktx
    - [x] https://github.com/mozilla-mobile/android-components/issues/8517
    - [x] https://github.com/mozilla-mobile/android-components/issues/9554
- support-utils
    - [x] https://github.com/mozilla-mobile/android-components/issues/9552

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7380)

**Comment by kbrosnan** [comment]
This is a hard requirement for shipping Gecko/Fenix v95. Google Play policy states that any [existing app must update to target API 30 (Android 11) by 2021-11-01](https://developer.android.com/distribute/play-policies#APILevel30).

**Comment by mcarare** [comment]
@Amejia481 Some of these require actually changing the `targetSdkVersion` because the replacement API/constants/methods are introduced only in SDK 30.  This would mean they should be all handled in the same PR and merged only when we actually change the `targetSdkVersion`.
Do you think there is another possible workflow or this is the only one?

**Comment by Amejia481** [comment]
> @Amejia481 Some of these require actually changing the `targetSdkVersion` because the replacement API/constants/methods are introduced only in SDK 30. This would mean they should be all handled in the same PR and merged only when we actually change the `targetSdkVersion`.
> Do you think there is another possible workflow or this is the only one?

In one pr, we could move the `targetSdkVersion` and add the `@Suppress("Deprecation")` to the deprecated APIs linking each issue where they will be addressed, then we can address  each issue individually. What do you think?

**Comment by mcarare** [comment]
Yes, that could be a better approach. I was also thinking of temporarily changing `kotlinOptions.allWarningsAsErrors` to `false`, but I think your proposal makes organizing things easier.

**Comment by mcarare** [comment]
@Amejia481 I see that there are also a couple of changes that cannot be "ignored" like API changes regarding nullability. I think all of these should be handled in a single PR that would serve as a "base" for the other changes that require handling deprecation issues.

**Comment by Amejia481** [comment]
Agree 👍🏽 , we should do all mandatory changes in a based PR to increase the `targetSdkVersion` and unlock the tasks for fixing the API deprecation that will be worked on individual PRs.
